name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Access API key variable
        run: |
          echo "API Key is ${{ vars.API_KEY }}"
